my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: brooklyndatapartner
      user: [username]
      role: [user role]

      # SSO config
      authenticator: externalbrowser

      database: analytics
      warehouse: DEVELOPER
      schema: dbt_fundamentals_kb
      threads: 1
      client_session_keep_alive: False
      query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false 
